### ISSUE TITLE
Labels don't save

### ISSUE THREAD

**Issue by quisp65** [piperun/torrent-clipper#1] opened 2019-01-31 13:57 UTC
When using with Qbittorrent the Labels don't save.  They work if options remain up and open in tab but if tab is closed they don't work and "Labels" are lost.   

Also the directory path doesn't work.  

Both these issues work with the Firefox extension, and I recognize it's a work in progress.

thanks for the work

**Comment by piperun** [comment] 2019-02-01 08:39
Hi!
Thanks for the issue, I noticed directory has some uncaught issues, so I'll try and get it fixed.
However the labels are technically saved, just that it doesn't show up on the option menu, which I'll look into.

**Comment by piperun** [comment] 2019-03-19 00:41
Alright so it seems I've fixed it, it should work now, I'm closing the issue if the issue still persist you can write here.

**Comment by maxcore** [comment] 2019-06-06 12:51
Not working for me , i need readd label every time i open chrome ..

**Comment by piperun** [comment] 2019-06-08 20:51
Hi! Thanks for the notice, unfortunately I need some additional information about the issue you're having:
Which version of the extension are you using? (Go into Extensions -> Torrent Clipper -> [Details])
What does the console say (Go into Extensions -> Torrent Clipper -> [Details] -> "background page")?

**Comment by maxcore** [comment] 2019-06-09 04:15
Version
0.2.9
-

nothing in the console

**Comment by piperun** [comment] 2019-06-09 20:46
Okay so could you explain in more detail what is it that you're having issue with and what do you expect to happen?

**Comment by maxcore** [comment] 2019-06-09 20:49
I add the label i save , work perfect . If i go in the config all label was remove it . 

If i close chrome i lost all label too

I need to put label inch time i open my chrome.

**Comment by piperun** [comment] 2019-06-10 12:45
Could you open background page and then add the label as you would do as usual and post if there's any errors popping up.

**Comment by maxcore** [comment] 2019-06-10 13:00
![Capture d’écran, le 2019-06-10 à 08 58 46](https://user-images.githubusercontent.com/4043787/59196930-02b34300-8b5e-11e9-8498-c20dca895927.png)
![Capture d’écran, le 2019-06-10 à 08 58 33](https://user-images.githubusercontent.com/4043787/59196935-05ae3380-8b5e-11e9-9d45-c822e60aa12a.png)


the download folder stay save but label not,
i reinstall the extention  and same way

**Comment by maxcore** [comment] 2019-06-10 13:01
![Capture d’écran, le 2019-06-10 à 09 01 05](https://user-images.githubusercontent.com/4043787/59197062-502fb000-8b5e-11e9-8fe0-d048869161ab.png)
when i comeback in the config

**Comment by piperun** [comment] 2019-06-11 13:31
I'll try and replicate the issue you're having.

**Comment by maxcore** [comment] 2019-06-11 14:14
I use chrome on mac mojave i will try in Windows tonight

**Comment by piperun** [comment] 2019-06-12 16:21
So I manage to reproduce the problem you're having and there is no error message so I'll have to dig down deeper and see what the problem could be.

**Comment by piperun** [comment] 2019-08-09 10:23
Hello! Sorry for no update, I may have fixed the issue, however it'll take a while before the extension is up online again.
In the meantime could you install the extension via github?

**Comment by piperun** [comment] 2019-10-29 07:49
Closing due to no one else reporting about this issue anymore and from my end, the features work as intended.

**Closed as completed by piperun** 2019-10-29 07:49 UTC
Labels: bug
